name: say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: self-hosted
    steps:
      - name: echo de un mensaje
        run: |
          echo "hello world"
          echo "pruebita"
