name: Deployment

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout del repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: fedetutti/pokedex-for-ci
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: run cat command
        run: cat .github/workflows/hello    
