name: Deployment

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout del repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: fedetutti/pokedex-for-ci
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Delete posible corrupt dependencies
        run: rm -rf node_modules
      - name: Install dependencies
        run: npm install --no-audit --no-fund
      - name: Lint
        run: npm run eslint
      - name: Clean cache
        run: npm cache clean --force
      - name: Openssl-provider update
        run: export NODE_OPTIONS=--openssl-legacy-provider
      - name: build
        run: npm run build
      - name: Test
        run: npm test